create table if not exists public.tasks (
    id bigint generated by default as identity primary key,
    clickup_task_id text not null unique,
    name text not null,
    last_seen_at timestamptz not null default now(),
    created_at timestamptz not null default now()
);

create table if not exists public.time_entries (
    id bigint generated by default as identity primary key,
    clickup_task_id text not null references public.tasks(clickup_task_id),
    task_name text not null,
    clickup_user_id text,
    start_time timestamptz not null,
    end_time timestamptz not null,
    start_ms bigint not null,
    end_ms bigint not null,
    duration_ms bigint not null,
    duration_minutes numeric(10, 2) not null,
    source text not null check (source in ('manual', 'timer')),
    status text not null default 'NOTREAD',
    created_at timestamptz not null default now()
);

alter table public.time_entries
    add column if not exists status text not null default 'NOTREAD';

create index if not exists idx_time_entries_clickup_task_id
    on public.time_entries(clickup_task_id);

create index if not exists idx_time_entries_start_time
    on public.time_entries(start_time);

drop view if exists public.powerbi_time_entries;

create view public.powerbi_time_entries as
select
    te.id,
    te.clickup_task_id,
    coalesce(t.name, te.task_name) as task_name,
    te.clickup_user_id,
    te.start_time,
    te.end_time,
    te.duration_minutes,
    round(te.duration_minutes / 60, 2) as duration_hours,
    te.source,
    te.status,
    te.created_at
from public.time_entries te
left join public.tasks t
    on t.clickup_task_id = te.clickup_task_id;

alter table public.tasks enable row level security;
alter table public.time_entries enable row level security;

grant usage on schema public to anon, authenticated;
grant select, insert, update on public.tasks to anon, authenticated;
grant select, insert on public.time_entries to anon, authenticated;
grant select on public.powerbi_time_entries to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

drop policy if exists "Allow app read tasks" on public.tasks;
create policy "Allow app read tasks"
on public.tasks
for select
to anon
using (true);

drop policy if exists "Allow app insert tasks" on public.tasks;
create policy "Allow app insert tasks"
on public.tasks
for insert
to anon
with check (true);

drop policy if exists "Allow app update tasks" on public.tasks;
create policy "Allow app update tasks"
on public.tasks
for update
to anon
using (true)
with check (true);

drop policy if exists "Allow app read time entries" on public.time_entries;
create policy "Allow app read time entries"
on public.time_entries
for select
to anon
using (true);

drop policy if exists "Allow app insert time entries" on public.time_entries;
create policy "Allow app insert time entries"
on public.time_entries
for insert
to anon
with check (true);
